# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rtunes}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adeptware"]
  s.date = %q{2009-12-03}
  s.default_executable = %q{rtunes}
  s.description = %q{Control iTunes remotely using Ruby OSA calls.}
  s.email = %q{contact@adeptware.com}
  s.executables = ["rtunes"]
  s.files = [
    "VERSION",
     "bin/rtunes",
     "lib/rtunes.rb"
  ]
  s.homepage = %q{http://github.com/adeptware/rtunes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Control iTunes remotely using Ruby OSA calls.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

